name: Build and Run .NET Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'  # Update this if using a different .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration debug

    - name: Run solution
      run: dotnet run --project "HiSuite Proxy/HiSuite Proxy.csproj"
