name: Build HiSuite Proxy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Ensure this is the correct version for your project

      # Install missing NuGet packages
      - name: Install NuGet packages
        run: |
          dotnet restore "HiSuite Proxy.sln"

      # Build the solution
      - name: Build solution
        run: |
          dotnet build "HiSuite Proxy.sln" --configuration Release --runtime win-x64

      # Upload the build artifact if successful
      - name: Upload build artifact
        if: success()  # Only run if the build succeeds
        uses: actions/upload-artifact@v3
        with:
          name: HiSuite-Proxy-Build
          path: |
            **/bin/Release/**
