name: Build and Run .NET Solution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.x' # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Add NuGet Packages
      run: |
        dotnet add "HiSuite Proxy/HiSuite Proxy.csproj" package BouncyCastle.Crypto --version 1.8.8
        dotnet add "HiSuite Proxy/HiSuite Proxy.csproj" package Titanium.Web.Proxy --version 3.1.1344

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run solution
      run: dotnet run --project "HiSuite Proxy/HiSuite Proxy.csproj"

    - name: Install MSBuild
      run: choco install visualstudio2019-buildtools -y --ignore-checksums
