name: Build and Upload Artifact

on:
  push:
    branches:
      - master  # Change this if your default branch is different

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild (if necessary)
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore dependencies
      run: nuget restore "HiSuite Proxy.sln"

    - name: Build Solution with MSBuild
      run: msbuild "HiSuite Proxy.sln" /p:Configuration=Release /p:Platform="Any CPU"

    - name: Publish for Windows Any CPU
      run: msbuild "HiSuite Proxy.sln" /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishUrl=./publish

    - name: Upload Artifact
      if: success()  # Only upload if the build and publish steps succeed
      uses: actions/upload-artifact@v3
      with:
        name: HiSuite-Proxy-Artifact
        path: ./publish  # The output directory from publish step
