name: Build HiSuite Proxy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Update this to the version of .NET used by your project

      # Restore NuGet packages
      - name: Restore dependencies
        run: nuget restore "HiSuite Proxy.sln"

      # Build the solution
      - name: Build solution
        run: msbuild "HiSuite Proxy.sln" /p:Configuration=Release

      # Upload the built artifact if the build succeeds
      - name: Upload build artifact
        if: success() # Only run if the build step succeeds
        uses: actions/upload-artifact@v3
        with:
          name: HiSuite-Proxy-Build
          path: |
            **/bin/Release/**
