name: Build and Upload Artifact

on:
  push:
    branches:
      - master  # Ensuring it runs only for the master branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # Make sure to use the correct .NET version

    - name: Restore dependencies
      run: dotnet restore "HiSuite Proxy.sln"

    - name: Build Solution
      run: dotnet build "HiSuite Proxy.sln" --configuration Release

    - name: Publish for Windows x64
      run: dotnet publish "HiSuite Proxy.csproj" --configuration Release --runtime win-x64 --output ./publish

    - name: Upload Artifact
      if: success()  # Only upload if the build and publish steps succeed
      uses: actions/upload-artifact@v3
      with:
        name: HiSuite-Proxy-Artifact
        path: ./publish  # The output path from the publish step
